export const FETCH_CHARACTERS = 'characters:FETCH_CHARACTERS'
export const FETCH_CHARACTERS_SUCCESS = 'characters:FETCH_CHARACTERS_SUCCESS'
export const FETCH_CHARACTERS_FAILURE = 'characters:FETCH_CHARACTERS_FAILURE'

export const FETCH_CHARACTER = 'characters:FETCH_CHARACTER'
export const FETCH_CHARACTER_SUCCESS = 'characters:FETCH_CHARACTER_SUCCESS'
export const FETCH_CHARACTER_FAILURE = 'characters:FETCH_CHARACTER_FAILURE'
